// Registro central de calculadoras: una única fuente de verdad para nav,
// home, sitemap y metadatos SEO.
export const CALCULATORS = [
  {
    slug: "calculadora-hipoteca",
    path: "/calculadora-hipoteca",
    name: "Calculadora de Hipoteca",
    shortName: "Hipoteca",
    description: "Calcula la cuota mensual de tu hipoteca, el interés total y el plazo, con tabla de amortización completa.",
    keyword: "calculadora de hipoteca",
    category: "hipotecas",
    icon: "home",
  },
  {
    slug: "calculadora-salario-neto",
    path: "/calculadora-salario-neto",
    name: "Calculadora de Sueldo Neto",
    shortName: "Sueldo Neto",
    description: "Convierte tu sueldo bruto anual en neto: Seguridad Social, IRPF estimado y cuánto recibes cada mes en tu nómina.",
    keyword: "calculadora de sueldo neto",
    category: "impuestos",
    icon: "wallet",
  },
  {
    slug: "calculadora-roi-inversion",
    path: "/calculadora-roi-inversion",
    name: "Calculadora de ROI de Inversión",
    shortName: "ROI Inversión",
    description: "Calcula el retorno de inversión (ROI) y la rentabilidad anual compuesta (CAGR) de cualquier inversión.",
    keyword: "calculadora roi inversión",
    category: "inversion",
    icon: "trending-up",
  },
  {
    slug: "amortizacion-credito",
    path: "/amortizacion-credito",
    name: "Calculadora de Amortización de Crédito",
    shortName: "Amortización de Crédito",
    description: "Genera la tabla de amortización mensual y anual de cualquier préstamo o crédito: capital, interés y saldo pendiente.",
    keyword: "amortización crédito",
    category: "hipotecas",
    icon: "table",
  },
  {
    slug: "calculadora-impuestos-renta",
    path: "/calculadora-impuestos-renta",
    name: "Calculadora de Impuestos sobre la Renta",
    shortName: "Impuestos (IRPF)",
    description: "Estima cuánto IRPF pagarás sobre tus ingresos anuales, con el desglose por tramos y tu tipo efectivo.",
    keyword: "impuesto sobre la renta",
    category: "impuestos",
    icon: "receipt",
  },
  {
    slug: "calculadora-interes-compuesto",
    path: "/calculadora-interes-compuesto",
    name: "Calculadora de Interés Compuesto",
    shortName: "Interés Compuesto",
    description: "Calcula cómo crece tu dinero con interés compuesto: capital inicial, aportaciones mensuales y rentabilidad anual.",
    keyword: "calculadora de interés compuesto",
    category: "inversion",
    icon: "percent",
  },
  {
    slug: "calculadora-iva",
    path: "/calculadora-iva",
    name: "Calculadora de IVA",
    shortName: "IVA",
    description: "Calcula el IVA de cualquier importe: añade el IVA a un precio sin impuestos o extrae la base de un precio final.",
    keyword: "calculadora de iva",
    category: "impuestos",
    icon: "receipt",
  },
  {
    slug: "calculadora-ahorro",
    path: "/calculadora-ahorro",
    name: "Calculadora de Ahorro",
    shortName: "Ahorro",
    description: "Calcula cuánto tienes que ahorrar cada mes para alcanzar tu meta de ahorro, según tu plazo y rentabilidad esperada.",
    keyword: "calculadora de ahorro",
    category: "inversion",
    icon: "piggy-bank",
  },
  {
    slug: "calculadora-alquilar-vs-comprar",
    path: "/calculadora-alquilar-vs-comprar",
    name: "Calculadora de Alquilar vs Comprar Vivienda",
    shortName: "Alquilar vs Comprar",
    description: "Compara el patrimonio acumulado a largo plazo si compras una vivienda con hipoteca o si alquilas e inviertes la diferencia.",
    keyword: "alquilar vs comprar vivienda",
    category: "hipotecas",
    icon: "scale",
  },
  {
    slug: "calculadora-cuota-autonomo",
    path: "/calculadora-cuota-autonomo",
    name: "Calculadora de Cuota de Autónomo",
    shortName: "Cuota Autónomo",
    description: "Estima tu cuota mensual de autónomo (RETA) según tus rendimientos netos, con la tarifa plana para nuevos autónomos.",
    keyword: "calculadora cuota autónomo",
    category: "impuestos",
    icon: "briefcase",
  },
  {
    slug: "calculadora-finiquito",
    path: "/calculadora-finiquito",
    name: "Calculadora de Finiquito",
    shortName: "Finiquito",
    description: "Calcula tu finiquito: parte proporcional de salario y pagas extra, vacaciones no disfrutadas e indemnización si corresponde.",
    keyword: "calculadora de finiquito",
    category: "impuestos",
    icon: "file-text",
  },
];

export function getCalculatorByPath(path) {
  return CALCULATORS.find((c) => c.path === path);
}

